server:
  port: 9999
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
#mybatis配置
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xin.entity.*
